{% extends "layout.phtml" %}

{% block content %}
<div id="cheatapp">
<a href="{{ path_for('index') }}">Index</a>

<h1>{{ book.name }} Cheatsheet</h1>

    <div>
        <h4>Show:</h4>
        <label>
            <input type="radio" name="show" value="all" v-model="cardVisibility"> All
        </label>

        <label>
            <input type="radio" name="show" value="cmd" v-model="cardVisibility"> Command
        </label>

        <label>
            <input type="radio" name="show" value="description" v-model="cardVisibility"> Description
        </label>


    </div>

    <div v-for="(group, cat) in cheatsheets">
        <h2>${cat}</h2>

        <div class="item" v-for="row in group" @click="toggleVisibility(row)">
            <div class="cmd" :style="{'background-color': row.bgcolor}"
                 v-if="cardVisibility == 'all' || cardVisibility == 'cmd' || row.show === true">
                <span v-html="row.cmd_rendered"></span>
            </div>

            <div class="metainfo" v-if="cardVisibility == 'all' || cardVisibility == 'description' || row.show === true">
                <div class="description">
                    <span v-html="row.description_rendered"></span>
                </div>

                <div class="details">
                    <span v-html="row.details_rendere"></span>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    BOOK_ID = {{ book.id }};
</script>

{% endblock %}